name: eikyusho
#repository:

packages:
  - app
  - packages/*

ide:
  intellij:
    enabled: true
    moduleNamePrefix: eikyusho_

command:
  bootstrap:
    environment:
      sdk: '>=3.4.0 <4.0.0'

    dependencies:
      # * Dev Utility
      meta: ^1.12.0 # ? Class annotations

    dev_dependencies:
      # ! Code Generation
      build_runner: any

scripts:
  generate:
    description: Generate necessary files for the project.
    exec: flutter pub run build_runner build --delete-conflicting-outputs
    packageFilters:
      dependsOn: [ build_runner ]

  fix:
    description: Run dart fix and apply the changes.
    exec: dart fix --apply

  test:selective_unit_test:
    description: Run Flutter tests for a specific package in this project.
    exec: flutter test --coverage --no-pub
    packageFilters:
      dirExists: test
      dependsOn: [ flutter_test ]

  test:
    description: Run all Flutter tests in this project.
    run: melos run test:selective_unit_test --no-select