name: eikyusho
description: "Free and open source novel reader for Android and iOS."
publish_to: 'none'

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  # * Core
  flutter:
    sdk: flutter

dev_dependencies:
  # * MonoRepo
  melos: ^6.0.0 # ? For managing monorepo
