name: localization
publish_to: 'none'

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  # * Core
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: any

flutter:
  generate: true