targets:
  $default:
    sources:
      - $package$
      - pubspec.*
      - lib/**

    builders:
      auto_route_generator:auto_route_generator:
        generate_for:
          - lib/src/**/presentation/views/**_page.dart # ? for @RoutePage
          - lib/config/router/app_router.dart   # ? for @AutoRouterConfig
          - lib/config/router/app_tabs.dart   # ? for AutoTabsRouter