name: app
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  # * Core
  flutter:
    sdk: flutter

  core:
    path: ../packages/core

  database:
    path: ../packages/database

  resources:
    path: ../packages/resources

  eikyusho_extensions:
    path: ../../extensions

  eikyusho_web_scraper:
    path: ../../web_scraper


  # * Routing
  go_router: ^14.2.0

  # * State Management
  flutter_bloc: ^8.1.6

  # * Dependency Injection
  get_it: ^7.7.0
  injectable: ^2.4.2

  # * Dev Utility
  equatable: ^2.0.5 # ? For value equality
  meta: ^1.12.0 # ? Class annotations

  # * UI
  carousel_slider: ^4.2.1

dev_dependencies:
  # ! Code Generation
  build_runner: any
  # * Generator Packages
  injectable_generator: ^2.6.1 # ? For Injectable

  # ! Testing
  flutter_test:
    sdk: flutter
  # * Testing Packages
  flutter_image_test_utils: ^1.0.0 # ? For testing images

  # * Utility
  flutter_native_splash: ^2.4.0 # ? For generating splash screen
  import_sorter: ^4.6.0 # ? For sorting imports

  linter: # ? For linting
    path: ../packages/linter

flutter:
  uses-material-design: true

  fonts:
    - family: Gotham
      fonts:
        - asset: ../packages/resources/assets/fonts/gotham-rnd-book.otf
          weight: 400
        - asset: ../packages/resources/assets/fonts/gotham-rnd-medium.otf
          weight: 500
        - asset: ../packages/resources/assets/fonts/gotham-rnd-bold.otf
          weight: 700
        - asset: ../packages/resources/assets/fonts/gotham-black.otf
          weight: 900

import_sorter:
  comments: false
