name: app
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  # * Core
  flutter:
    sdk: flutter

  core:
    path: ../packages/core

  database:
    path: ../packages/database

  resources:
    path: ../packages/resources

  # * Routing
  auto_route: ^8.1.3

  # * State Management
  flutter_bloc: ^8.1.5

  # * Dependency Injection
  get_it: ^7.7.0
  injectable: ^2.4.1

  # * Dev Utility
  equatable: ^2.0.5 # ? For value equality
  meta: ^1.12.0 # ? Class annotations

  # * UI
  carousel_slider: ^4.2.1

dev_dependencies:
  # ! Code Generation
  build_runner: any
  # * Generator Packages
  auto_route_generator: ^8.0.0 # ? For AutoRoute
  injectable_generator: ^2.6.1 # ? For Injectable

  # ! Testing
  flutter_test:
    sdk: flutter
  # * Testing Packages
  flutter_image_test_utils: ^1.0.0 # ? For testing images

  # * Utility
  flutter_native_splash: ^2.4.0 # ? For generating splash screen

  linter: # ? For linting
    path: ../packages/linter

flutter:
  uses-material-design: true
