name: core
publish_to: 'none'

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  # * Core
  flutter:
    sdk: flutter

  resources:
    path: ../resources

  # * Network
  dio: ^5.4.3+1

  # * App Utilities
  path: ^1.9.0  # ? File system
  path_provider: ^2.1.3 # ? File system
  hive: ^2.2.3 # ? User preferences
  shared_preferences: ^2.2.3 # ? Basic local storage

  # * Dev Utility
  equatable: ^2.0.5 # ? For value equality
  logger: ^2.3.0 # ? Logging
  meta: ^1.12.0 # ? Class annotations

dev_dependencies:
  # * Utility
  linter: # ? For linting
    path: ../linter
