name: core
publish_to: 'none'

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  # * Core
  flutter:
    sdk: flutter

  resources:
    path: ../resources

  # * Network
  dio: ^5.4.3+1

  # * Dev Utility
  meta: ^1.12.0 # ? Class annotations

dev_dependencies:
  # * Utility
  linter: # ? For linting
    path: ../linter
